#!/bin/bash
USERNAME=$1
PASSWORD=$2

cookie=`java -jar target/n-cube-cli-1.0.0-SNAPSHOT-jar-with-dependencies.jar nce-auth --u ${USERNAME} --p ${PASSWORD}`
echo "${cookie}"
version=`java -jar target/n-cube-cli-1.0.0-SNAPSHOT-jar-with-dependencies.jar nce-getappversion --cookie ${cookie} --app Devops.Test`
echo "VERSION=${version}"
